# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#default: &default
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000


development:
  adapter: postgresql
  encoding: utf8
  database: theoddcircle_development
  pool: 5
  username: postgres
  password: westlife

test:
  adapter: postgresql
  encoding: utf8
  database: theoddcircle_test
  pool: 5
  username: postgres
  password: westlife
